function [fitresult, gof] = createFit(wavelengths, voltages)
%CREATEFIT(WAVELENGTHS,VOLTAGES)
%  Create a fit.
%
%  Data for 'Band_Gap' fit:
%      X Input : wavelengths
%      Y Output: voltages
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Feb-2022 12:41:26


%% Fit: 'Band_Gap'.
[xData, yData] = prepareCurveData( wavelengths, voltages );

% Set up fittype and options.
ft = fittype( 'poly1' );
excludedPoints = excludedata( xData, yData, 'Indices', [1:490, 520:700] );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Band_Gap' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'voltages vs. wavelengths', 'Excluded voltages vs. wavelengths', 'Band_Gap', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'wavelengths', 'Interpreter', 'none' );
ylabel( 'voltages', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, excludedPoints, 'residuals' );
legend( h, 'Band_Gap - residuals', 'Excluded voltages vs. wavelengths', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'wavelengths', 'Interpreter', 'none' );
ylabel( 'voltages', 'Interpreter', 'none' );
grid on


