function [fitresult, gof] = StraightLineFit(w_straightline, v_straightline, std_straighline, wavelengths, voltages)
%CREATEFIT1(W_STRAIGHTLINE,V_STRAIGHTLINE,STD_STRAIGHLINE)
%  Create a fit.
%
%  Data for 'Straight Line Fit' fit:
%      X Input : w_straightline
%      Y Output: v_straightline
%      Weights : std_straighline
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 16:23:30

% figures no display in LaTeX
set(groot,'defaultAxesTickLabelInterpreter','latex');  
set(groot,'defaulttextinterpreter','latex');
set(groot,'defaultLegendInterpreter','latex');

%% Fit: 'Straight Line Fit'.

[xData, yData, weights] = prepareCurveData(w_straightline, v_straightline, std_straighline );

% Set up fittype and options.
ft = fittype('poly1');
opts = fitoptions('Method', 'LinearLeastSquares');
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure('Name', 'Straight Line Fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData, 'predobs', 0.999 );
legend( h, 'voltages vs. wavelengths with deviation', 'Straight Line Fit', 'Lower bounds (Straight Line Fit)', 'Upper bounds (Straight Line Fit)', 'Location', 'NorthWest');
hold on
% Label axes
xlabel('Wavelengths $(\lambda)$');
ylabel('Voltages (V)');
xlim([min(xData) max(xData)])
ylim([0 max(yData)])
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'Straight Line Fit - residuals', 'Zero Line', 'Location', 'NorthWest');
% Label axes
xlabel('Wavelengths $(\lambda)$');
ylabel('Voltages (V)');

grid on


% Create a figure for the plots.
figure('Name', 'Fit with all wavelengths');

% Plot fit with data.
plot( fitresult, xData, yData, 'predobs');
hold on
plot(wavelengths, voltages)

% Label axes
xlabel('Wavelengths $(\lambda)$');
ylabel('Voltages (V)');
xlim([min(wavelengths) max(wavelengths)])
ylim([0 max(voltages)])
grid on

% calculation of band gap

% parameters for graph and coefficients

coefficients = coeffvalues(fitresult);

bandgap_wavelength = -coefficients(2)/coefficients(1);
disp(['The bandgap of GaAs is: ', num2str(bandgap_wavelength)])

x = linspace(0,1200,1200);
LOBF_y = x*coefficients(1) + coefficients(2);
%p = predint(fitresult,wavelengths,0.68,'observation','on');

% plots line of best fit -- lambda vs V
% Create a figure for the plots.

figure( 'Name', 'Band_Gap_With_LineOfBestFit' );

plot(fitresult, wavelengths, voltages, 'predobs', 0.68);
%hold on
%plot(wavelengths, p)
hold on
%plot(x, LOBF_y,'--','color','r');
%hold on
plot(w_straightline, v_straightline, 'k*');
hold on
plot(bandgap_wavelength,0, 'k*','MarkerSize', 10);
xlabel('Wavelengths $(\lambda)$')
ylabel('Voltages (V)')
xlim([min(wavelengths) max(wavelengths)])
ylim([0 max(voltages)])

disp('finished')

p = predint(fitresult,wavelengths,0.90,'observation','on')
figure( 'Name', 'Band Gap Calculation' );
plot(fitresult, wavelengths, voltages,'b-'), hold on, plot(wavelengths, p, 'm--')
plot(w_straightline, v_straightline, 'k*');
hold on
plot(bandgap_wavelength,0, 'k*','MarkerSize', 10);
xlabel('Energy $(eV)$')
ylabel('Voltages (V)')
legend('off')
xlim([min(wavelengths) 1.7])
ylim([0 max(voltages)])
set(gca,'FontSize',16)

figure('Name', 'Alpha squared')
hold on
plot(energy_ev, squarealpha)
plot(x,y)
plot(x, p, 'm--')
legend('off')
xlabel('Energy $(eV)$')
ylabel('Alpha Squared $(\alpha^2)$')
set(gca,'FontSize',16)
xlim([1.3 1.45])
ylim([0 max(squarealpha)])



figure( 'Name', 'Alpha squared' )
errorbar(energy_ev,alpha_1,err_alpha)

figure( 'Name', 'Alpha squared' )
hold on
errorbar(energy_ev(2:end), squarealpha, err_alpha(2:end)*2, 'vertical')
plot(x,y, '*')
plot(x, p, 'm--')
legend('off')
xlabel('Energy $(eV)$')
ylabel('Alpha Squared $(\alpha^2)$')
set(gca,'FontSize',16)
xlim([1.3 1.45])
ylim([0 max(squarealpha)])


%%

p = predint(fittedmodel_squared,energy_ev,0.95);

figure( 'Name', 'Alpha squared' )
hold on
errorbar(energy_ev,alpha_squared,err_alpha)
plot(energy_ev, p, 'm--')
xlabel('Energy $(eV)$')
ylabel('Alpha Squared $(\alpha^2)$')
set(gca,'FontSize',16)
xlim([1.3 1.45])
ylim([0 max(alpha_squared)])

figure( 'Name', 'Alpha squared LOBF' )
hold on
plot(energy_ev, p, 'm--')
plot(energy_ev(523:544), squarealpha(523:544),'k*')
plot(fittedmodel_squared)
xlabel('Energy $(eV)$')
ylabel('Alpha Squared $(\alpha^2)$')
set(gca,'FontSize',16)
legend('off')
xlim([min(energy_ev(523:544)) max(energy_ev(523:544))])
ylim([0 max(squarealpha(523:544))])

 p = predint(fittedmodel_squared,energy_ev,0.95);

figure( 'Name', 'Alpha squared' )
hold on
errorbar(energy_ev(523:544),squarealpha(523:544),err_alpha(523:544),'k*', 'horizontal')
plot(fittedmodel_squared)
plot(energy_ev, p, 'm--')
plot(energy_ev, squarealpha, 'b-')
xlabel('Energy $(eV)$')
ylabel('$\alpha^2$ (cm$)^{-2}$')
set(gca,'FontSize',16)
xlim([1.3 1.45])
ylim([0 max(squarealpha)])
legend('off')

p = predint(fittedmodel_squared,energy_ev,0.95);

figure( 'Name', 'Alpha squared' )
hold on
errorbar(energy_ev,squarealpha,2*err_alpha,'k*')
plot(energy_ev, p, 'm--')
xlabel('Energy $(eV)$')
ylabel('$\alpha^2$ $(cm)^{-2}$')
set(gca,'FontSize',16)
xlim([1.3 1.45])
ylim([0 max(squarealpha)])

%%

lw = length(energy_ev);
wwave = h*c./(energy_ev.*10^(-9)*1.6*10^-19);

for n = 1:lw
wwaveup = wwave(n) +3;
wwavelow = wwave(n) - 3;

engup = h*c./(wwaveup.*10^(-9)*1.6*10^-19);
englow = h*c./(wwavelow.*10^(-9)*1.6*10^-19);

delteng(n) = engup - englow;

end

errbareng = delteng./2;




   







